### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by devandroidios** [Iskenderun-Technical-University/ymg-donem-projesi-visionGPT#18]
```
FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
[stderr] 
The following dependencies do not satisfy the required version:
[stderr] 
project ':expo-app-auth' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 3m 13s
```

**Comment by mert-donmez** [comment]
Hi devandroidios,

Actually, there should be no problems in .apk and .abb build part.
 A plugin version is incompatible as far as I can see in `project ':expo-app-auth' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21`. The reason for this may be related to your local computer.


I'm working on it. I'll give information. I'm not closing this issue yet.

**Comment by mert-donmez** [comment]
i noticed this error came after android and ios prebuild. Necessary plugin version fixes will be made. 
The reason for prebuild was to test Google auth.

**Comment by mert-donmez** [comment]
Issue has been fixed. 

The plugin version `"org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21"` in the build.gradle file where the error originated was made 1.5.20 and the build problem was solved.

Instead of opening a new issue on a different issue related to Build, you can comment under this topic.
I'm closing this issue. 

Thanks.
